services:
  db_main:
    image: postgres:15-alpine
    env_file:
      - .env
      - backend/.env
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - db_main_data:/var/lib/postgresql/data
    ports:
    - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${BACKEND_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - dev
    
  db_users:
    image: postgres:15-alpine
    env_file:
      - .env
      - users_api/.env
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
    - "5434:5432"
    volumes:
      - db_users_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USERS_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - dev

  backend:
    build: ./backend
    env_file:
      - .env
      - backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  users-api:
    build: ./users_api
    env_file:
      - .env
      - users_api/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - users-api
    ports:
      - "80:80"
      - "443:443"

volumes:
  db_main_data:
  db_users_data:
